name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Depend
      run: sudo apt-get install -y build-essential libgtest-dev
    - name: make
      run: make
    - name: chmod
      run: chmod +x ./test1
    - name: run test
      run: ./test1
